### ISSUE TITLE
Week view position events from the top and display text in the middle

### ISSUE THREAD

**Issue by Toomas633** [Serhioromano/bootstrap-calendar#783]
## 1st problem
How can i display the events on one line, so that each day they start from the top not where the last one ends? I tried changing the z-index but no luck there.

![image](https://user-images.githubusercontent.com/52831344/170786439-9768e4db-9349-4db7-b741-9d197c6b8d9a.png)

## 2nd problem
How can i change the text to be in the middle of the event box. I have tried editing css .  And how could i expand the space between the time and text, adding spaces or html characters has been without progress.

**Comment by cablegunmaster** [comment]
1st problem 
A total rewrite of the Html / CSS. since all is done in : 
https://github.com/Serhioromano/bootstrap-calendar/blob/master/tmpls/week-days.html
Its now just cells underneath each other without an table, this should be changed into a table if you want this functionality.

And the 2nd problem its added by Javascript; in the variable 
"event.title" , so look up the title part, and change it accordingly;

Its in the global variable: Calendar.prototype.getTitle  so go look this up and change accordingly.

If you do not know how to change these I would recommend asking someone near you who is good in coding.
Who knows html / templating, using javascript and templating.

**Comment by Neozxz** [comment]
十分感谢，邮件已经收到！
